spring:
  application:
    name: shipping-service
  datasource:
    url: jdbc:postgresql://db.qwutrcnbvlrswcsbfzil.supabase.co:5432/postgres
    username: postgres
    password: RushikeshBhosale@08
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  rabbitmq:
    addresses: amqps://aursdcav:mI88FXsJgSK7wakjVyauY4APJMRKhNr6@gerbil.rmq.cloudamqp.com/aursdcav

server:
  port: 8083
