spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres
    username: postgres.qwutrcnbvlrswcsbfzil
    password: RushikeshBhosale@08
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  rabbitmq:
    addresses: amqps://aursdcav:mI88FXsJgSK7wakjVyauY4APJMRKhNr6@gerbil.rmq.cloudamqp.com/aursdcav

server:
  port: ${PORT:8081}
